name: Deploy Wikipedia Chatbot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Test if app runs
      run: |
        python -c "
        import streamlit as st
        import wikipedia
        print('✅ All imports working!')
        "
    
    - name: List files
      run: ls -la

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Streamlit Cloud
      uses: streamlit/streamlit-app-action@v0.0.4
      with:
        app-path: main.py
        cloud-url: ${{ secrets.STREAMLIT_CLOUD_URL }}
        streamlit-token: ${{ secrets.STREAMLIT_TOKEN }}
